blog/urls.py
from blog.views import PostLV
from django.conf.urls import url
urlpatterns = [
    # :8000/post
    url( r'^post/$', PostLV.as_view(), name='post_list' ),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, BookmarkView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'blog/', include('blog.urls', namespace='blog')),

    url(r'^bookmark/$', BookmarkLV.as_view(),
        name='index'),
    url(r'^bookmark/(?P<pk>\d+)/$', BookmarkDV.as_view(),
        name='detail')
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100,
                                   blank=True,
                                   help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from blog.models import Post

# Create your views here.

class PostLV(ListView):
    model = Post
    context_object_name = 'posts'

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

class BookmarkView(TemplateView):
    template_name = ""

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1>Blog List</h1>

    {% for post in posts %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.description }}</p>
    {% endfor %}

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bookmark detail</title>
</head>
<body>
    <div id="content">
        <h1>{{ object.title }}</h1>

        <ul>
            <li>URL: <a href="{{ object.url }}" target="_blank">
                {{ object.url }}
            </a></li>
        </ul>

    </div>

</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bookmark list</title>
</head>
<body>
    <div id="content">
        <h1>bookmark list</h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>



    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main page</title>
    <link href="https://fonts.googleapis.com/css?family=Pattaya|Sunflower:300" rel="stylesheet">
    <style>
        body{
            background-image: url("{% static 'img/Leaves.png' %}");
            background-repeat: no-repeat;
            background-size: 100%;
            background-position: center top;
        }
        #subject{
            font-size: 100px;
            text-align: center;
            color: orange;
            font-family: 'Pattaya', sans-serif;
        }
        #title{
            font-size: 150px;
            text-align: center;
            color: forestgreen;
            font-family: 'Pattaya', sans-serif;
            background-color: rgba(0, 255, 191, 0.1);
        }
        #made{
            font-size: 50px;
            text-align: center;
            font-family: 'Pattaya', sans-serif;
            color: darkgray;
        }
        .big{
            color: hotpink;
        }
        ul li{
            display: inline-block;
            font-size:25px;
            font-family: 'Pattaya', sans-serif;
            color: orangered;
            border: 5px double orange;
            border-radius: 10px;
            margin: 20px 15px;
            padding:5px;
        }
        ul{
            text-align: center;
            background-color: rgba(255, 255, 230, 0.5);
        }
        a{
            text-decoration: none;
            color: orangered;
        }

    </style>
</head>
<body>
    <h1 id="subject">DM4 WEB SERVICE MAKER</h1>
    <h1 id="title">Django Framework</h1>
    <p id="made">Made by <span class="big">R</span>yan.<span class="big">A</span>hn</p>

    <ul>
        <li><a href="{% url 'index' %}" target="_blank">Bookmark</a></li>
        <li><a href="{% url 'blog:post_list' %}" target="_blank">Blog</a></li>
        <li><a>Photo</a></li>
    </ul>

</body>
</html>